name = "anixo-backend-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[build]
command = "npm install"

[env.production]
# Add production specific bindings or env vars here if needed
