const colors = {
  light: {
    text: "#ffffff",
    tint: "#dc2626",
    background: "#0b0e14",
    foreground: "#ffffff",
    card: "#111827",
    cardForeground: "#ffffff",
    primary: "#dc2626",
    primaryForeground: "#ffffff",
    secondary: "#1f2937",
    secondaryForeground: "#e5e7eb",
    muted: "#1f2937",
    mutedForeground: "#9ca3af",
    accent: "#dc2626",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1f2937",
    input: "#1f2937",
  },
  dark: {
    text: "#ffffff",
    tint: "#dc2626",
    background: "#0b0e14",
    foreground: "#ffffff",
    card: "#111827",
    cardForeground: "#ffffff",
    primary: "#dc2626",
    primaryForeground: "#ffffff",
    secondary: "#1f2937",
    secondaryForeground: "#e5e7eb",
    muted: "#1f2937",
    mutedForeground: "#9ca3af",
    accent: "#dc2626",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1f2937",
    input: "#1f2937",
  },
  radius: 8,
};

export default colors;
